#!/bin/bash

# define some vars
prog="${0##*/}"
SUBDIRECTORY_OK=Yes
NONGIT_OK=Yes
OPTIONS_KEEPDASHDASH=
OPTIONS_STUCKLONG=
OPTIONS_SPEC="\
${prog/-/ } [-f|--foo] [-b|--bar <arg>] [--baz <baz-arg>] <args>

Do something with <args>.
--
 Option group header (use --no-OPTION to disable --OPTION)
f,foo         some nifty option --foo
b,bar=arg     some cool option --bar with an argument named arg1

 Another option group header
q,qux!        an option without --no-qux counterpart
baz!=baz-arg  another cool option --baz with a named argument
 
h,help!       show this help message and exit
"

# parse options and create useful shell functions, $GIT_DIR, $GIT_OBJECT_DIRECTORY 
. "$(git --exec-path)/git-sh-setup"

# print help output if called with no args
if (( ! $# )); then
	usage
fi

# parse options
foo=0
echo "$@"
while (( $# )); do
	case "$1" in
		-f|--foo)
			foo=1
		;;
		--no-foo)
			foo=0
		;;
		-b|--bar)
			shift
			bar="$1"
		;;
		--no-bar)
			unset bar
		;;
		--baz)
			shift
			baz="$1"
		;;
		--)
			shift
			break
		;;
		-*)
			die "unimplemented option (this is a bug): $1"
			#usage
		;;
		*)
			break
		;;
	esac
	shift
done

# do something with remaining args
#cd_to_toplevel
echo "$PWD> $prog $*"
#do_thing "$@"

